apiVersion: v1
kind: Service
metadata:
  name: rag-detector
spec:
  type: NodePort
  selector:
    app: rag-detector
  ports:
    - name: http
      port: 8501
      targetPort: http
      nodePort: 30501
    - name: metrics
      port: 9108
      targetPort: metrics
      nodePort: 30908
